name: Reusable Workflow(YAML -> JSON to use fromJSON function)

on:
  workflow_call:
    inputs:
      yaml_file_path:
        required: true
        type: string
    outputs:
      result:
        value: ${{ jobs.main.outputs.result }}

jobs:
  main:
    name: yaml to json
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.convert.outputs.output }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - uses: fabasoad/data-format-converter-action@v0
        id: convert
        with:
          input: ${{ inputs.yaml_file_path }}
          from: 'yaml'
          to: 'json'
